version: '3'
services:

  postgres:
    image: postgres:9.6.19-alpine
    env_file:
      env.secret
    environment:
      - POSTGRES_USER=psql
    networks:
      - databases
    ports:
      - 5432:5432
    volumes:
      - ${POSTGRES_VOLUME_DATA:-./volumes/postgres}:/var/lib/postgresql/data:Z
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  databases:
    external: true
